# Site settings
title: "Yangspace"
description: "Resume page for Sejong Yang"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sejong Yang"
resume_title:                   "Student, Researcher, Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kingsj0405@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(02) 2123-5709"
resume_contact_address:         "50, Yonsei-ro, Seodaemun-gu, Seoul, Republic of Korea"

resume_header_contact_info:     "50, Yonsei-ro, Seodaemun-gu, Seoul, Republic of Korea • (02) 2123-5709 • kingsj0405@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I'm a student pursuing a Doctor's degree in Computer Science. I'm studying under <a href='https://sites.google.com/site/seonjookim/'>Professor Seonju Kim</a>. Currently researching on Computer Vision, Machine Learning and especially Deep learning. I have experience with Cross-platform Mobile, Cloud Computing and Backend Development.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kingsj0405"
  resume_twitter_url:           "https://twitter.com/kingsj0405_twit"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/kingsj0405"
  resume_linkedin_url:          "https://www.linkedin.com/in/sejong-yang-242696116/"
  resume_instagram_url:         "https://www.instagram.com/kingsj0405/"
  resume_website_url:           "https://yangspace.co.kr/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
